default: &default
  adapter: postgresql
  encoding: utf8
  template: template0
  username: admin
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ttd-api-development

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: ttd-api-production
  username: ttd-api
  password: <%= ENV['TTD-API-PASSWORD'] %>
